version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4 #To able to use docker commands
  heroku: circleci/heroku@2.0.0 #Allow us to use heroku orb's commands
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies...”
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Running tests...”
          npm run test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run: echo "<< pipeline.git.tag >>"
      - docker/build:
          image: joseyc/node-app
          tag: << pipeline.git.tag >>
      - docker/push:
          image: joseyc/node-app
          tag: << pipeline.git.tag >>
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: joseyc/node-app
    steps:
      - checkout
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
          severity-threshold: high
  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - heroku/install
  #     - checkout     
  #     - run:
  #         name: Heroku Container Push
  #         command: |
  #           heroku container:login
  #           heroku container:push web -a joseyc-su-devops
  #           heroku container:release web -a joseyc-su-devops
          # Push image to heroku's contaienr registry
          # Relese deploy image from heroku's container registry
workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
              branches:
                only:
                  - main
      - test:
          requires:
            - build
      - scan:
          requires:
            - build
      - build-and-push:
          requires:
            - test
          filters:
            # branches:
            #   ignore: /.*/ 
            tags:
              only: /.*/
      # - deploy:
      #     requires:
      #       - build-and-push 
