version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  build:
    docker:
      - image: cimg/node:16.10

      - image: docker:stable

    steps:
      - checkout
      - setup_remote_docker
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
          echo "Building docker image..."
          docker build --tag node-app .
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
